// expo-env.d.ts is gitignored and only generated by `expo start`, so a fresh
// checkout (CI) typechecks without it. Reference expo/types directly so tsc
// never depends on a generated file.
/// <reference types="expo/types" />
